### ISSUE TITLE
drop dom lib dependency 

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/snapper#1]
aside from initializing via the enhance event, it should be simple to make this jquery/shoestring independent

**Comment by simevidas** [comment]
It would be worth researching if there are any important browser bugs that would be introduced by dropping jQuery, I think.

**Comment by piyushchauhan2011** [comment]
Yeah agreed, dropping jquery would be worth it as mostly of the libraries are moving or moved away from jquery long time now.

**Comment by staabm** [comment]
a zero dependency version would be awesome!

**Comment by hacknug** [comment]
Any plan on tackling this soon-ish?

**Comment by janKollars** [comment]
I started working on this issue (https://github.com/janKollars/snapper/tree/remove-jquery). I am not sure though if I approached it correctly so far. Instead of initialising it using
```javascript
$('.snapper').snapper()
```
the slider is / the sliders are now initialised using a NodeList as argument.
```javascript
snapper(document.querySelectorAll('.snapper'))
```

Wouldn't it be preferable to provide a `Snapper` class, which is instantiated using a single node?
Then, `goto` or `getIndex` could be called like this
```javascript
const snapperInstance = new Snapper(document.querySelector('.snapper'))
...
snapperInstance.getIndex()
```
instead of
```javascript
const snapperElements = document.querySelectorAll('.snapper')
snapper(snapperElements)
...
snapper(snapperElements, 'getIndex')
```

**Comment by scottjehl** [comment]
Thanks for the update. If that effort ends up mostly keeping parity with the API here, we'd love to see a PR.

As for how we're working on it lately, I've converted Snapper to a jQuery-free web component over here https://github.com/filamentgroup/wc-experiments/blob/master/snapper/wc-snapper.js

Demo is here. It's very much an early pass but mostly functional with all features here. I am guessing we'll rename it and put it in a repo that doesn't make any claims of snapper compatibility. 
https://filamentgroup.github.io/wc-experiments/snapper/

**Comment by janKollars** [comment]
I really like the idea of having a snapper web component! This would be very cool!
The PR is ready. It kept parity with the jQuery API + introduced an API for plain JavaScript (they are documented in the README).
