### ISSUE TITLE
Mixed-content issue on demo page

### ISSUE THREAD

**Issue by simevidas** [filamentgroup/snapper#19]
URL: https://filamentgroup.github.io/snapper/demo/

The style sheet is referenced via a `http:` URL causing it to be blocked as active mixed content by browsers when the demo page is loaded over HTTPS.

![issue](https://cloud.githubusercontent.com/assets/716405/16107608/aede35ca-339d-11e6-88a2-99043fd70fef.png)

**Comment by zachleat** [comment]
Fixed by @johnbender originally but needed an updated `gh-pages` (just completed)
