### ISSUE TITLE
Add an github pages with demo

### ISSUE THREAD

**Issue by kosssi** [filamentgroup/snapper#22]
Thanks for your lib ;)

**Comment by francoismassart** [comment]
[Snapper Demo](http://filamentgroup.github.io/snapper/demo/) ?

**Comment by kosssi** [comment]
May be you can add demo url on the github descriptif in Website ;)

**Comment by toddparker** [comment]
@kosssi and @francoismassart - Thanks for the heads up, I just added demo links to the readme:

https://github.com/filamentgroup/snapper#demo

**Comment by kosssi** [comment]
thanks ;)
