### ISSUE TITLE
Namespace js classes

### ISSUE THREAD

**Issue by jonespen** [filamentgroup/snapper#25]
http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#javascript-namespaces-js

Imo it would make it simpler to separate the classes are used for javascript actions and styling. I can submit a pull req if any interest

**Comment by scottjehl** [comment]
Thanks for the suggestion. This idea is a good one but we're not interested in the upgrade complications of changing our classes at this time. Thanks!
