### ISSUE TITLE
How can we invoke the `next();` method ?

### ISSUE THREAD

**Issue by francoismassart** [filamentgroup/snapper#27]
Hi,
I'd like to be able to trigger the sliding of the next slide every 5 seconds...
Right now, I did it using a setInterval + something like 

`$('.snapper_nextprev_next').trigger('click');`

but this is causing a side effect while the `click` event is bubbling...

is there another way to call the `next()` method ?

Thank you for your help

**Comment by scottjehl** [comment]
At the moment, no there's not a better way than what you've suggested. I think it would be best for us to work on a refactor soon that exposes a component instance with several methods. We've patched in a means of calling some methods already by re-calling snapper() on an element and passing method names as arguments. For example, `$mySnapper.snapper( "goto", 3 );` `$mySnapper.snapper( "getIndex" );` are currently offered and could get you most of what you'd want here, but the arrow button components have some logic to support looping when there's no slide to advance to, and simply iterating goto isn't going to quite get what you need. 

We should either expose more of these string methods or more typical object methods to expose a few more internal helpers.
