### ISSUE TITLE
iphone lock-in

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/snapper#3]
iPhone iOS 9

worth testing:
1. scroll down to carousel
2. swipe to advance carousel
3. try to scroll back up, with touch starting on carousel

**Comment by francoismassart** [comment]
I did try on a local machine via the Apple's Simulator and I could not reproduce this issue...
Could you host your demo on jsfiddle or somewhere else online?

**Comment by scottjehl** [comment]
Bug no longer present.
