### ISSUE TITLE
Vertical snap points ?

### ISSUE THREAD

**Issue by piyushchauhan2011** [filamentgroup/snapper#44]
Do we have a support vertical snap points, I'm just curious to get an example so I can have a play with it. Currently the demo contains only horizontal slides example.

**Comment by scottjehl** [comment]
Snapper's purpose is to be less of a general/full-featured polyfill for snap points, and more of a helper to enable snap point based carousel viewers. In that way, we have no plans at this time to support vertical snapping. Thanks for the suggestion though!
