### ISSUE TITLE
Is it possible to identify the active slide programmatically?

### ISSUE THREAD

**Issue by ceteri** [filamentgroup/snapper#66]
Is it possible to identify the active slide programmatically?

In other words, could I make a call in JavaScript to find out which slide has most recently snapped into view?

**Comment by ceteri** [comment]
Watching the `snapper.snap` event dispatched by `snapEvent()` works *most* of the time:
```
$(".snapper").bind("snapper.snap", function(event, data){
  slide_id = data.activeSlides[0].id;
};
```

However, the problem is that  `snapEvent()` does not get dispatched when someone swipes all the way to the first or last slide.

Digging in a bit, this seems to work fine:
```
var selected_thumb = $( "a.snapper_nav_item-selected" )[ 0 ];
```

Then set a timer in JavaScript to check and update periodically, e.g., every half second.

Also, there's an edge case where the active slide is not well-defined when a [URI target](http://w3c.github.io/html-reference/a.html#a.attrs.target) specifies a specific slide. 
One workaround is to use a naming convention for the `id` attributes within the `snapper_nav` thumbnail list, then simulate a user click once the page loads. 
For example, given these thumbnails:
```
  <div id="nav" class="snapper_nav">
    <a id="a_slide1" href="#slide1"><img src="p0000.jpg" alt=""/></a>
    <a id="a_slide2" href="#slide2"><img src="p0001.jpg" alt=""/></a>
    <a id="a_slide3" href="#slide3"><img src="p0002.jpg" alt=""/></a>
    <a id="a_slide4" href="#slide4"><img src="p0003.jpg" alt=""/></a>
    <a id="a_slide5" href="#slide5"><img src="p0004.jpg" alt=""/></a>
    <a id="a_slide6" href="#slide6"><img src="p0005.jpg" alt=""/></a>
  </div>
```

Then to correct that edge case on load:
```
$(function() {
  // click the slide selected by the URI
  var slide_id = window.location.hash.substr(1);
  $("div#nav #a_" + slide_id).trigger("click");
});
```

**Comment by Paul-Hebert** [comment]
In 4.0 they added a `snapper.active` event that fires when a slide becomes active. I don't know if that would suffer the same issues but may be worth looking into!
